[package]
name = "platform_prototype"
version = "0.1.0"
edition = "2021"

[dependencies]
#raylib = { git = "https://github.com/raylib-rs/raylib-rs.git" }
#raylib = { git = "https://github.com/raylib-rs/raylib-rs.git", features = ["opengl_21"] }
raylib = "5.5.1"
